//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bayosi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class besleme
    {
        public int besleme_id { get; set; }
        public int personel_tc_no { get; set; }
        public int mama_id { get; set; }
        public System.DateTime tarih { get; set; }
        public string mama_miktarı { get; set; }
    
        public virtual mama mama { get; set; }
        public virtual personel personel { get; set; }
    }
}
