//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bayosi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hayvan
    {
        public hayvan()
        {
            this.sahiplenme = new HashSet<sahiplenme>();
            this.tedavi = new HashSet<tedavi>();
        }
    
        public int kupe_no { get; set; }
        public int tur_id { get; set; }
        public int ırk_ıd { get; set; }
        public int gelis_sebebi_id { get; set; }
        public Nullable<int> cikis_sebebi_id { get; set; }
        public string hayvan_ad { get; set; }
        public byte[] hayvan_resim { get; set; }
        public System.DateTime barinak_gelis_tarihi { get; set; }
        public Nullable<System.DateTime> barinak_cikis_tarihi { get; set; }
        public string sahip_isim { get; set; }
        public string sahip_adress { get; set; }
        public Nullable<int> sahip_telno { get; set; }
    
        public virtual cikis_sebebi cikis_sebebi { get; set; }
        public virtual gelis_sebebi gelis_sebebi { get; set; }
        public virtual irk irk { get; set; }
        public virtual tur tur { get; set; }
        public virtual ICollection<sahiplenme> sahiplenme { get; set; }
        public virtual ICollection<tedavi> tedavi { get; set; }
    }
}
