//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bayosi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilac
    {
        public ilac()
        {
            this.tedavi = new HashSet<tedavi>();
        }
    
        public int ilac_id { get; set; }
        public string ilac_ad { get; set; }
        public string aciklama { get; set; }
    
        public virtual ICollection<tedavi> tedavi { get; set; }
    }
}
