//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bayosi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public string kullaniciAdi { get; set; }
        public string parola { get; set; }
        public int tcNo { get; set; }
    
        public virtual personel personel { get; set; }
    }
}
