//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bayosi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mama
    {
        public mama()
        {
            this.besleme = new HashSet<besleme>();
        }
    
        public int mama_id { get; set; }
        public string mama_adi { get; set; }
        public int tur_id { get; set; }
        public string marka { get; set; }
    
        public virtual ICollection<besleme> besleme { get; set; }
        public virtual tur tur { get; set; }
    }
}
