//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bayosi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meslek
    {
        public meslek()
        {
            this.personel = new HashSet<personel>();
        }
    
        public int meslek_id { get; set; }
        public string meslek_adi { get; set; }
        public string meslek_açiklama { get; set; }
    
        public virtual ICollection<personel> personel { get; set; }
    }
}
