//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bayosi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class barinak_otomasyonEntities3 : DbContext
    {
        public barinak_otomasyonEntities3()
            : base("name=barinak_otomasyonEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<besleme> besleme { get; set; }
        public virtual DbSet<cikis_sebebi> cikis_sebebi { get; set; }
        public virtual DbSet<gelis_sebebi> gelis_sebebi { get; set; }
        public virtual DbSet<hayvan> hayvan { get; set; }
        public virtual DbSet<ilac> ilac { get; set; }
        public virtual DbSet<irk> irk { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
        public virtual DbSet<mama> mama { get; set; }
        public virtual DbSet<mesaj> mesaj { get; set; }
        public virtual DbSet<meslek> meslek { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<sahiplenme> sahiplenme { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tedavi> tedavi { get; set; }
        public virtual DbSet<tur> tur { get; set; }
        public virtual DbSet<yonetici> yonetici { get; set; }
    }
}
