//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bayosi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sahiplenme
    {
        public int sahiplenme_id { get; set; }
        public int kupe_no { get; set; }
        public int sahiplenen_tc { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public Nullable<int> ev_tel { get; set; }
        public int cep_tel { get; set; }
        public string adress { get; set; }
        public System.DateTime sahiplenme_tarihi { get; set; }
    
        public virtual hayvan hayvan { get; set; }
    }
}
