//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bayosi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tedavi
    {
        public int tedavi_id { get; set; }
        public int kupe_no { get; set; }
        public int personel_tc_no { get; set; }
        public Nullable<int> ilac_id { get; set; }
        public Nullable<int> doz { get; set; }
        public string aciklama { get; set; }
    
        public virtual hayvan hayvan { get; set; }
        public virtual ilac ilac { get; set; }
        public virtual personel personel { get; set; }
    }
}
